#pragma once

#define CONTAINER_DEQUE "CONTAINER_DEQUE"
#define CONTAINER_LIST "CONTAINER_LIST"
#define CONTAINER_VECTOR "CONTAINER_VECTOR"

#define DATA_FOLDER "./data/"
#define GRADE_MIN 1
#define GRADE_MAX 10

#define RESULT_TYPE_MEAN "RESULT_TYPE_MEAN"
#define RESULT_TYPE_MEDIAN "RESULT_TYPE_MEDIAN"
#define RESULT_TYPE_BOTH "RESULT_TYPE_BOTH"

#define TIME_PRECISION 5